export const CREATE_PIE = 'CREATE_PIE'
export const FETCH_PIE = 'FETCH_PIE'
export const UPDATE_PIE = 'UPDATE_PIE'

export const FETCH_PIES = 'FETCH_PIES'

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'
    
export const LOGOUT = 'USERS_LOGOUT'

export const GETALL_REQUEST = 'USERS_GETALL_REQUEST'
export const GETALL_SUCCESS = 'USERS_GETALL_SUCCESS'
export const GETALL_FAILURE = 'USERS_GETALL_FAILURE'