export const CREATE_PIE = 'CREATE_PIE'
export const FETCH_PIE = 'FETCH_PIE'
export const UPDATE_PIE = 'UPDATE_PIE'

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'
    
export const LOGOUT = 'USERS_LOGOUT'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const CURRENT_USER_REFRESH_REQUEST = 'CURRENT_USER_REFRESH_REQUEST'
export const CURRENT_USER_REFRESH_SUCCESS = 'CURRENT_USER_REFRESH_SUCCESS'
export const CURRENT_USER_REFRESH_FAILURE = 'CURRENT_USER_REFRESH_FAILURE'